/**
 * index-rebuilder.ts — Regenerates .tracker/00-INDEX.md from spec reality.
 *
 * This is the sole authority for producing .tracker/00-INDEX.md.
 * The output mirrors the hand-authored format exactly:
 *   - Front-matter with name, type, version
 *   - Progress Dashboard table (all milestones)
 *   - Current Focus section with per-spec table + Next Action block
 *   - Blockers section
 *   - Status Legend
 *   - Archived Milestones section
 *
 * Generated files carry the do-not-edit header.
 *
 * Testable: accepts TrackerState directly (no filesystem calls here).
 */

import { basename } from "node:path";
import type { TrackerState, MilestoneEntry, SpecEntry } from "./tracker-reader.ts";
import { isTerminalMilestone, collectBrokenSpecs } from "./tracker-reader.ts";
import { CURRENT_SCHEMA_VERSION } from "./version.ts";

const GENERATED_HEADER =
  "<!-- Generated by darius. Do not edit; run `darius index --rebuild`. -->";

const STATUS_LEGEND = `## Status Legend

Item-level markers:

- \`[x]\` — Verified (implementation complete, tests pass)
- \`[ ]\` — Pending (not started)
- \`[~]\` — In Progress (actively being worked on)
- \`[!]\` — Blocked (has dependency, can't proceed)
- \`[-]\` — Skipped (intentionally not implementing)

Milestone-level statuses (terminal: **Complete**, **Skipped**, **Deferred**, **Closed**):

- **Not Started** — no progress yet
- **In Progress** — some items verified or active
- **Blocked** — one or more items blocked
- **Complete** — every item is verified or skipped, with at least one verified
- **Skipped** — every item is skipped (no verified items)
- **Deferred** — closed by author via README \`status: Deferred\`; darius treats this as terminal regardless of item state
- **Closed** — closed by author via README \`status: Closed\` (remaining scope abandoned); terminal regardless of item state`;

/**
 * Rebuild the full .tracker/00-INDEX.md content from the current state.
 *
 * Returns the file content as a string. Caller is responsible for writing.
 */
export function rebuildIndexDoc(state: TrackerState): string {
  const lines: string[] = [];

  lines.push(GENERATED_HEADER);
  lines.push("");
  lines.push("---");
  lines.push(`name: ${state.projectName} Tracker`);
  lines.push(`schema_version: ${CURRENT_SCHEMA_VERSION}`);
  lines.push("type: main-index");
  lines.push("version: 2");
  lines.push("---");
  lines.push("");
  lines.push(`# ${state.projectName} — Tracker`);
  lines.push("");
  lines.push(`Implementation progress overview for the ${state.projectName} project.`);
  lines.push("");

  // ---- Progress Dashboard ----
  lines.push("## Progress Dashboard");
  lines.push("");
  lines.push("| Milestone | Name | Progress | Verified | Status |");
  lines.push("|-----------|------|----------|----------|--------|");

  for (const m of state.milestones) {
    const bar = buildProgressBar(m.verified, m.total);
    const pct = buildProgressPct(m.verified, m.total);
    lines.push(
      `| M${m.number} | ${m.name} | ${bar} ${pct}% | ${m.verified}/${m.total} | ${m.status} |`,
    );
  }

  lines.push("");

  // ---- Current Focus ----
  const focusMilestone = state.milestones.find((m) => !isTerminalMilestone(m.status));

  if (focusMilestone) {
    lines.push("## Current Focus");
    lines.push("");
    lines.push(`### M${focusMilestone.number} — ${focusMilestone.name}`);
    lines.push("");
    lines.push("| Spec | Verified | Status |");
    lines.push("|------|----------|--------|");

    for (const spec of focusMilestone.specs) {
      const statusCell = buildSpecStatusCell(spec);
      lines.push(
        `| ${spec.file} | ${spec.view.verifiedCount}/${spec.view.totalCount} | ${statusCell} |`,
      );
    }

    lines.push("");

    const nextTask = findNextTask(focusMilestone);
    if (nextTask) {
      lines.push("### Next Action");
      lines.push(
        `**Spec:** \`${nextTask.file}\` — ${nextTask.specTitle}`,
      );
      lines.push(`**Task:** ${nextTask.label}`);
      lines.push("**Status:** Pending");
    } else {
      lines.push("### Next Action");
      lines.push("All tasks in current focus milestone are complete.");
    }
  } else {
    lines.push("## Current Focus");
    lines.push("");
    lines.push("All milestones complete.");
  }

  lines.push("");

  // ---- Blockers ----
  lines.push("## Blockers");
  lines.push("");

  const blockers = collectBlockers(state);
  if (blockers.length === 0) {
    lines.push("None");
  } else {
    for (const b of blockers) {
      lines.push(`- ${b.label} (${b.file})`);
    }
  }

  lines.push("");

  // ---- Broken Specs (only rendered when non-empty) ----
  const broken = collectBrokenSpecs(state);
  if (broken.length > 0) {
    lines.push("## ⚠ Broken Specs (excluded from counts above)");
    lines.push("");
    for (const b of broken) {
      lines.push(`- **${b.file}** (${b.milestoneSlug}): ${b.error}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(STATUS_LEGEND);
  lines.push("");

  // ---- Archived Milestones (scanned from .tracker/archive/*.md) ----
  lines.push("## Archived Milestones");
  lines.push("");
  if (state.archivedMilestones.length === 0) {
    lines.push("_None yet_");
  } else {
    for (const a of state.archivedMilestones) {
      const date = a.archivedDate ? ` — archived ${a.archivedDate}` : "";
      lines.push(`- [${a.name}](${a.file})${date}`);
    }
  }
  lines.push("");

  // ---- Rituals (recurring work; see rituals/<slug>/ritual.md) ----
  lines.push("## Rituals");
  lines.push("");
  const rituals = state.rituals ?? [];
  if (rituals.length === 0) {
    lines.push("_No rituals yet_");
  } else {
    lines.push("| Ritual | Cadence | Last run | Next due |");
    lines.push("|--------|---------|----------|----------|");
    for (const r of rituals) {
      lines.push(
        `| ${r.slug} | ${r.cadence ?? "—"} | ${r.lastRun ?? "—"} | ${r.due ?? "—"} |`,
      );
    }
  }
  lines.push("");

  // ---- Vigils (one-shot pending verifications; see vigils/<slug>.md) ----
  lines.push("## Vigils");
  lines.push("");
  const vigils = state.vigils ?? [];
  const openVigils = vigils.filter((v) => v.verdict === null || v.verdict === "");
  const closedVigilCount = vigils.length - openVigils.length;
  if (openVigils.length === 0 && closedVigilCount === 0) {
    lines.push("_No vigils yet_");
  } else {
    if (openVigils.length > 0) {
      lines.push("| Vigil | Waiting on | Due | Opened | From |");
      lines.push("|-------|------------|-----|--------|------|");
      for (const v of openVigils) {
        lines.push(
          `| ${v.slug} | ${v.until ?? "—"} | ${v.due ?? "—"} | ${v.opened ?? "—"} | ${v.from ?? "—"} |`,
        );
      }
    }
    if (closedVigilCount > 0) {
      if (openVigils.length > 0) lines.push("");
      lines.push(`_${closedVigilCount} closed_`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Progress bar helpers
// ---------------------------------------------------------------------------

function buildProgressBar(verified: number, total: number): string {
  if (total === 0) return "░░░░░░░░░░";
  const filled = Math.round((verified / total) * 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
}

function buildProgressPct(verified: number, total: number): number {
  if (total === 0) return 0;
  return Math.round((verified / total) * 100);
}

// ---------------------------------------------------------------------------
// Spec status cell
// ---------------------------------------------------------------------------

function buildSpecStatusCell(spec: SpecEntry): string {
  if (spec.effectiveStatus === "Waiting") {
    const depsOn = spec.view.depends_on ?? [];
    const unmetDep = depsOn[0] ?? "";
    const depFile = basename(unmetDep);
    return `Waiting (waiting on: ${depFile})`;
  }
  return spec.view.computedStatus;
}

// ---------------------------------------------------------------------------
// Next task
// ---------------------------------------------------------------------------

type NextTask = {
  label: string;
  file: string;
  specTitle: string;
};

function findNextTask(milestone: MilestoneEntry): NextTask | null {
  for (const spec of milestone.specs) {
    if (spec.effectiveStatus === "Waiting") continue;
    if (spec.view.computedStatus === "Complete") continue;
    if (spec.view.computedStatus === "Skipped") continue;

    for (const item of spec.view.checklistItems) {
      if (item.state === "pending" || item.state === "in_progress") {
        return { label: item.label, file: spec.file, specTitle: spec.view.title };
      }
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Blockers
// ---------------------------------------------------------------------------

type Blocker = {
  label: string;
  file: string;
};

function collectBlockers(state: TrackerState): Blocker[] {
  const blockers: Blocker[] = [];
  for (const milestone of state.milestones) {
    for (const spec of milestone.specs) {
      for (const item of spec.view.checklistItems) {
        if (item.state === "blocked") {
          blockers.push({ label: item.label, file: spec.file });
        }
      }
    }
  }
  return blockers;
}
