/**
 * migrate.ts — Deterministic migration from legacy tracker shapes to v9-canonical.
 *
 * Detects the tracker version and computes the set of changes needed.
 * In dry-run mode: prints a diff to stdout with no filesystem writes.
 * In apply mode: writes all changes atomically and records a migration log.
 *
 * Exported for testability:
 *   detectVersion       — classify current tracker shape
 *   planMigration       — compute list of changes (no I/O writes)
 *   applyMigration      — execute changes + write log
 *   formatDiff          — render unified-diff-style output
 *
 * The loose-mode parser (parseFrontmatterLoose) is used ONLY inside this module.
 * All other CLI paths continue to use the strict schemas.
 */

import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  mkdirSync,
  unlinkSync,
} from "node:fs";
import { join, basename, relative, dirname } from "node:path";
import { parseFrontmatter, serializeFrontmatter } from "./markdown/frontmatter.ts";
import { atomicWriteFileSync } from "./atomic.ts";
import { readTrackerState } from "./tracker-reader.ts";
import { rebuildIndexDoc } from "./index-rebuilder.ts";
import { CURRENT_SCHEMA_VERSION } from "./version.ts";
import { isWorklogIndexFile } from "./worklog.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATED_HEADER =
  "<!-- Generated by darius. Do not edit; run `darius index --rebuild`. -->";
/** The header before 0.77.0: an index that has it is current too. */
const PREVIOUS_GENERATED_HEADER =
  "<!-- Generated by tracker CLI. Do not edit; run `tracker index --rebuild`. -->";

// ---------------------------------------------------------------------------
// Version detection
// ---------------------------------------------------------------------------

export type TrackerVersion = "v1" | "v8" | "v9";

/**
 * Detect the current tracker shape by examining the .tracker/ directory.
 *
 * v1: .tracker/ contains *.md spec files at root (no milestone M{N}-* folders)
 * v8: milestone folders exist but specs have status:/verified: in frontmatter,
 *     OR 00-INDEX.md lacks the generator header,
 *     OR worklog entries use mixed-prefix conventions
 * v9: clean canonical state (nothing to migrate)
 */
export function detectVersion(trackerRoot: string): TrackerVersion {
  const entries = readdirSync(trackerRoot);

  // Look for milestone folders (M{N}-* pattern)
  const milestoneFolders = entries.filter((e) => {
    const full = join(trackerRoot, e);
    return statSync(full).isDirectory() && /^M\d+-.+$/.test(e);
  });

  // v1: spec files (.md) at root level that are NOT 00-INDEX.md
  const rootSpecFiles = entries.filter((e) => {
    if (!e.endsWith(".md")) return false;
    if (e === "00-INDEX.md") return false;
    const full = join(trackerRoot, e);
    return statSync(full).isFile();
  });

  if (milestoneFolders.length === 0 && rootSpecFiles.length > 0) {
    return "v1";
  }

  // Check for v8 drift signals
  if (milestoneFolders.length > 0) {
    // Check 1: 00-INDEX.md missing generator header
    const indexPath = join(trackerRoot, "00-INDEX.md");
    if (existsSync(indexPath)) {
      const indexContent = readFileSync(indexPath, "utf-8");
      if (!indexContent.includes(GENERATED_HEADER) && !indexContent.includes(PREVIOUS_GENERATED_HEADER)) {
        return "v8";
      }
    }

    // Check 2: Any spec has status: or verified: in frontmatter
    for (const folder of milestoneFolders) {
      const fullFolder = join(trackerRoot, folder);
      const specFiles = getSpecFilesInFolder(fullFolder);
      for (const specPath of specFiles) {
        const raw = readFileSync(specPath, "utf-8");
        const { data } = parseFrontmatterLoose(raw);
        if ("status" in data || "verified" in data) {
          return "v8";
        }
      }
    }
  }

  return "v9";
}

// ---------------------------------------------------------------------------
// Migration planning
// ---------------------------------------------------------------------------

export type MigrationChangeAction = "created" | "modified" | "moved";

export type MigrationChange = {
  step: string;
  file: string; // relative path from trackerRoot parent
  action: MigrationChangeAction;
  reason: string;
  /** New content (undefined for moves where content unchanged) */
  newContent?: string;
  /** For moves: the destination path (absolute) */
  destPath?: string;
};

export type MigrationPlan = {
  version: TrackerVersion;
  changes: MigrationChange[];
};

/**
 * Compute all changes required to bring the tracker to v9-canonical state.
 * Does NOT perform any writes — pure computation.
 */
export function planMigration(opts: {
  trackerRoot: string;
  fromVersion?: TrackerVersion;
}): MigrationPlan {
  const { trackerRoot } = opts;
  const version = opts.fromVersion ?? detectVersion(trackerRoot);

  if (version === "v9") {
    return { version, changes: [] };
  }

  const changes: MigrationChange[] = [];
  const repoRoot = dirname(trackerRoot);

  if (version === "v1") {
    // migrateV1ToV2: move flat *.md files into M1-<name>/ folder
    const rootSpecFiles = readdirSync(trackerRoot).filter((e) => {
      if (!e.endsWith(".md")) return false;
      if (e === "00-INDEX.md") return false;
      const full = join(trackerRoot, e);
      return statSync(full).isFile();
    });

    if (rootSpecFiles.length > 0) {
      const slug = "migrated";
      const folderName = "M1-migrated";
      const folderPath = join(trackerRoot, folderName);

      // Scaffold a minimal README for the synthetic milestone
      const readmeContent = buildMilestoneReadme({
        name: "Migrated Specs",
        slug,
        date: todayIsoString(),
        target: "TBD",
        owner: "unknown",
      });

      changes.push({
        step: "migrateV1ToV2",
        file: relative(repoRoot, join(folderPath, "00-README.md")),
        action: "created",
        reason: "scaffold milestone folder for flat v1 specs",
        newContent: readmeContent,
        destPath: join(folderPath, "00-README.md"),
      });

      for (const specFile of rootSpecFiles) {
        const srcPath = join(trackerRoot, specFile);
        const destPath = join(folderPath, specFile);
        const content = readFileSync(srcPath, "utf-8");
        changes.push({
          step: "migrateV1ToV2",
          file: relative(repoRoot, destPath),
          action: "moved",
          reason: `move flat v1 spec into milestone folder ${folderName}`,
          newContent: content,
          destPath,
        });
      }
    }

    // Also run v8 migration steps after v1->v2
    addV8Changes({ trackerRoot, changes, repoRoot, tempMilestoneFolders: ["M1-migrated"] });
  } else {
    // v8: run drift-correction steps only
    addV8Changes({ trackerRoot, changes, repoRoot, tempMilestoneFolders: [] });
  }

  // Always regenerate index as final step
  changes.push({
    step: "regenerateIndex",
    file: relative(repoRoot, join(trackerRoot, "00-INDEX.md")),
    action: "modified",
    reason: "regenerate 00-INDEX.md with canonical generator header",
    destPath: join(trackerRoot, "00-INDEX.md"),
    // newContent is computed at apply time from TrackerState
  });

  return { version, changes };
}

// ---------------------------------------------------------------------------
// Migration application
// ---------------------------------------------------------------------------

export type ApplyResult = {
  appliedCount: number;
  logPath: string | null; // null in dry-run
  changes: MigrationChange[];
};

/**
 * Apply all migration changes to the filesystem (or describe them in dry-run).
 *
 * In apply mode:
 *   - All writes go through atomicWriteFileSync
 *   - A migration log is written to .tracker/.migration-<ISO-date>.log
 *
 * In dry-run mode:
 *   - No filesystem writes
 *   - Returns changes for diff formatting
 */
export function applyMigration(opts: {
  trackerRoot: string;
  plan: MigrationPlan;
  dryRun: boolean;
}): ApplyResult {
  const { trackerRoot, plan, dryRun } = opts;
  const { changes } = plan;

  if (changes.length === 0) {
    return { appliedCount: 0, logPath: null, changes: [] };
  }

  if (dryRun) {
    return { appliedCount: changes.length, logPath: null, changes };
  }

  // --- Apply mode ---
  const timestamp = new Date().toISOString();
  const logLines: string[] = [];

  // Separate index regeneration from other changes
  const indexChange = changes.find((c) => c.step === "regenerateIndex");
  const otherChanges = changes.filter((c) => c.step !== "regenerateIndex");

  for (const change of otherChanges) {
    if (!change.destPath) continue;

    // Ensure parent directory exists
    const parentDir = dirname(change.destPath);
    if (!existsSync(parentDir)) {
      mkdirSync(parentDir, { recursive: true });
    }

    const content = change.newContent ?? "";
    atomicWriteFileSync(change.destPath, content);

    // For "moved" actions, remove the source file
    // Source is the file at trackerRoot/<basename(destPath)>
    if (change.action === "moved") {
      const srcPath = join(trackerRoot, basename(change.destPath));
      if (existsSync(srcPath) && srcPath !== change.destPath) {
        try {
          unlinkSync(srcPath);
        } catch {
          // Best effort
        }
      }
    }

    logLines.push(
      `[${timestamp}] STEP=${change.step} FILE=${change.file} ACTION=${change.action} REASON=${change.reason}`,
    );
  }

  // Regenerate the index last (needs actual TrackerState from disk)
  if (indexChange) {
    try {
      const state = readTrackerState(trackerRoot);
      const indexContent = rebuildIndexDoc(state);
      const indexPath = indexChange.destPath ?? join(trackerRoot, "00-INDEX.md");
      atomicWriteFileSync(indexPath, indexContent);
      logLines.push(
        `[${timestamp}] STEP=regenerateIndex FILE=${indexChange.file} ACTION=modified REASON=regenerate 00-INDEX.md with canonical generator header`,
      );
    } catch {
      // Index rebuild might fail on v1 before folders are set up; non-fatal
    }
  }

  // Write the migration log
  const logFileName = `.migration-${formatISOForFileName(new Date())}.log`;
  const logPath = join(trackerRoot, logFileName);
  atomicWriteFileSync(logPath, logLines.join("\n") + "\n");

  return { appliedCount: changes.length, logPath, changes };
}

// ---------------------------------------------------------------------------
// Diff formatting
// ---------------------------------------------------------------------------

/**
 * Format a migration plan as a unified-diff-style string for stdout.
 */
export function formatDiff(opts: {
  plan: MigrationPlan;
  dryRun: boolean;
}): string {
  const { plan, dryRun } = opts;
  const lines: string[] = [];

  if (dryRun) {
    lines.push("# DRY RUN — tracker migrate");
    lines.push("");
  }

  if (plan.changes.length === 0) {
    lines.push(`Detected version: ${plan.version}`);
    lines.push("Nothing to migrate — tracker is already v9-canonical.");
    return lines.join("\n");
  }

  lines.push(`Detected version: ${plan.version}`);
  lines.push(`Changes: ${plan.changes.length} file(s)`);
  lines.push("");

  // Group by step
  const byStep: Record<string, MigrationChange[]> = {};
  for (const change of plan.changes) {
    if (!byStep[change.step]) byStep[change.step] = [];
    byStep[change.step]!.push(change);
  }

  for (const [step, stepChanges] of Object.entries(byStep)) {
    lines.push(`## Step: ${step}`);
    lines.push("");
    for (const change of stepChanges) {
      lines.push(`  ${change.action.toUpperCase().padEnd(8)} ${change.file}`);
      lines.push(`           Reason: ${change.reason}`);
      if (change.newContent !== undefined && change.action !== "moved") {
        // Show a brief preview (first 5 non-empty lines)
        const preview = change.newContent
          .split("\n")
          .filter((l) => l.trim())
          .slice(0, 5)
          .map((l) => `  + ${l}`)
          .join("\n");
        if (preview) {
          lines.push(preview);
        }
      }
    }
    lines.push("");
  }

  if (dryRun) {
    lines.push(`## Step: stampSchemaVersion`);
    lines.push("");
    lines.push(`  MODIFIED .tracker/00-INDEX.md`);
    lines.push(`           Reason: write schema_version: ${CURRENT_SCHEMA_VERSION} as final atomic step`);
    lines.push("");
    lines.push("Run with --apply to execute these changes.");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Migration report log format
// ---------------------------------------------------------------------------

/**
 * Build the content for a dry-run report (stdout only, no .log file).
 */
export function formatDryRunReport(changes: MigrationChange[]): string {
  const lines: string[] = ["# DRY RUN — tracker migrate"];
  const timestamp = new Date().toISOString();
  for (const change of changes) {
    lines.push(
      `[${timestamp}] STEP=${change.step} FILE=${change.file} ACTION=${change.action} REASON=${change.reason}`,
    );
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Internal: v8 drift-correction changes
// ---------------------------------------------------------------------------

function addV8Changes(opts: {
  trackerRoot: string;
  changes: MigrationChange[];
  repoRoot: string;
  tempMilestoneFolders: string[];
}): void {
  const { trackerRoot, changes, repoRoot, tempMilestoneFolders } = opts;

  // Collect current milestone folders (from disk)
  const existingFolders = readdirSync(trackerRoot).filter((e) => {
    const full = join(trackerRoot, e);
    return statSync(full).isDirectory() && /^M\d+-.+$/.test(e);
  });

  // Also include folders that will be created by v1 migration
  const allFolderNames = [...new Set([...existingFolders, ...tempMilestoneFolders])];

  for (const folderName of allFolderNames) {
    const folderPath = join(trackerRoot, folderName);

    // Only process if the folder exists (temp folders don't yet)
    if (!existsSync(folderPath)) continue;

    const specFiles = getSpecFilesInFolder(folderPath);
    for (const specPath of specFiles) {
      const raw = readFileSync(specPath, "utf-8");
      const cleaned = stripDerivedFieldsLoose(raw);
      if (cleaned !== raw) {
        changes.push({
          step: "migrateLegacyFrontmatter",
          file: relative(repoRoot, specPath),
          action: "modified",
          reason: "stripped status: and verified: from frontmatter",
          newContent: cleaned,
          destPath: specPath,
        });
      }

      // normalizeDates: convert datetime strings to plain YYYY-MM-DD
      const afterStrip = cleaned;
      const normalized = normalizeDateStringsInFile(afterStrip);
      if (normalized !== afterStrip) {
        // Update or add to the existing change for this file
        const existingIdx = changes.findIndex(
          (c) => c.destPath === specPath && c.step === "migrateLegacyFrontmatter",
        );
        if (existingIdx >= 0) {
          changes[existingIdx]!.newContent = normalized;
          changes[existingIdx]!.reason += "; normalized date fields";
        } else {
          changes.push({
            step: "normalizeDates",
            file: relative(repoRoot, specPath),
            action: "modified",
            reason: "converted datetime strings to plain YYYY-MM-DD",
            newContent: normalized,
            destPath: specPath,
          });
        }
      }
    }
  }

  // normalizeWorklog: re-write worklog files if present
  const worklogDir = join(trackerRoot, "worklog");
  if (existsSync(worklogDir)) {
    // Generated `00-` index files are CLI output, not worklogs — rewriting
    // their bullets would edit a file whose only legitimate author is
    // `tracker worklog index`.
    const worklogFiles = readdirSync(worklogDir).filter(
      (f) => f.endsWith(".md") && !isWorklogIndexFile(f),
    );
    for (const wf of worklogFiles) {
      const wfPath = join(worklogDir, wf);
      const raw = readFileSync(wfPath, "utf-8");
      const normalized = normalizeWorklogPrefixes(raw);
      if (normalized !== raw) {
        changes.push({
          step: "normalizeWorklog",
          file: relative(repoRoot, wfPath),
          action: "modified",
          reason: "normalized worklog entry bullet prefix to -",
          newContent: normalized,
          destPath: wfPath,
        });
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Loose-mode parser (used ONLY inside this module)
// ---------------------------------------------------------------------------

type LooseDocument = {
  data: Record<string, unknown>;
  content: string;
};

/**
 * Loose-mode frontmatter parser. Wraps the strict parser and handles:
 * - Date instances (tolerated, not converted to cause parse failures)
 * - List bullets that aren't `-` (handles `*` and `+`)
 * - Indentation drift in frontmatter values
 *
 * Falls back from strict to loose with a warning on parse failure.
 * Used ONLY by migrate; other paths use the strict parseFrontmatter.
 */
function parseFrontmatterLoose(raw: string): LooseDocument {
  try {
    return parseFrontmatter(raw);
  } catch {
    // Fall back: try with alternative bullet normalization
    const normalized = raw
      .replace(/^(\s*)\* \[/gm, "$1- [") // * bullets → -
      .replace(/^(\s*)\+ \[/gm, "$1- ["); // + bullets → -
    try {
      return parseFrontmatter(normalized);
    } catch {
      // If still failing, return an empty-data document
      const fmMatch = /^---\n([\s\S]*?)\n---/.exec(raw);
      if (!fmMatch) return { data: {}, content: raw };
      const content = raw.slice((fmMatch[0] ?? "").length);
      return { data: {}, content };
    }
  }
}

// ---------------------------------------------------------------------------
// Strip derived fields (loose, for migrate use only)
// ---------------------------------------------------------------------------

function stripDerivedFieldsLoose(raw: string): string {
  const { data, content } = parseFrontmatterLoose(raw);

  const DERIVED_FIELDS = ["status", "verified"];
  const hasDerived = DERIVED_FIELDS.some((f) => f in data);
  if (!hasDerived) return raw;

  const cleaned: Record<string, unknown> = { ...data };
  for (const field of DERIVED_FIELDS) {
    delete cleaned[field];
  }

  const serialized = serializeFrontmatter(cleaned, content);
  return serialized.endsWith("\n") ? serialized : `${serialized}\n`;
}

// ---------------------------------------------------------------------------
// Date normalization
// ---------------------------------------------------------------------------

const DATETIME_RE = /^(\d{4}-\d{2}-\d{2})T\d{2}:\d{2}:\d{2}/;

function normalizeDateStringsInFile(raw: string): string {
  const { data, content } = parseFrontmatterLoose(raw);

  const dateFields = ["updated", "started", "target"];
  let changed = false;
  const normalized: Record<string, unknown> = { ...data };

  for (const field of dateFields) {
    const val = normalized[field];
    if (typeof val === "string") {
      const m = DATETIME_RE.exec(val);
      if (m) {
        normalized[field] = m[1];
        changed = true;
      }
    } else if (val instanceof Date) {
      normalized[field] = dateToIsoDateString(val);
      changed = true;
    }
  }

  if (!changed) return raw;

  const serialized = serializeFrontmatter(normalized, content);
  return serialized.endsWith("\n") ? serialized : `${serialized}\n`;
}

function dateToIsoDateString(d: Date): string {
  const year = d.getUTCFullYear();
  const month = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

// ---------------------------------------------------------------------------
// Worklog normalization
// ---------------------------------------------------------------------------

/**
 * Normalize worklog bullet prefixes: replace `* ` and `+ ` at line start with `- `.
 */
function normalizeWorklogPrefixes(raw: string): string {
  return raw.replace(/^(\s*)[\*\+] /gm, "$1- ");
}

// ---------------------------------------------------------------------------
// Milestone README scaffold
// ---------------------------------------------------------------------------

function buildMilestoneReadme(opts: {
  name: string;
  slug: string;
  date: string;
  target: string;
  owner: string;
}): string {
  return `---
name: ${opts.name}
slug: ${opts.slug}
started: '${opts.date}'
target: ${opts.target}
owner: ${opts.owner}
status: Not Started
---

# ${opts.name}

## Goal

<!-- Migrated from v1 flat tracker. Describe the goal here. -->

## Why this matters

<!-- TODO: why does this matter? -->

## Success criteria

- <!-- TODO: success criterion -->

## Non-goals

- <!-- TODO: non-goal -->

## Specs in this milestone

<!-- rebuilt from file listing; do not edit manually -->

## Lessons

<!-- populated by /darius-enrich when the milestone completes -->
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getSpecFilesInFolder(folderPath: string): string[] {
  const entries = readdirSync(folderPath).sort();
  const specs: string[] = [];
  for (const entry of entries) {
    if (!entry.endsWith(".md")) continue;
    if (entry === "00-README.md") continue;
    const full = join(folderPath, entry);
    if (statSync(full).isFile()) {
      specs.push(full);
    }
  }
  return specs;
}

function todayIsoString(): string {
  const d = new Date();
  const year = d.getUTCFullYear();
  const month = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function formatISOForFileName(d: Date): string {
  return d.toISOString().replace(/:/g, "-").replace(/\.\d+Z$/, "Z");
}

// ---------------------------------------------------------------------------
// High-level runner (used by bin/tracker.mts)
// ---------------------------------------------------------------------------

export type MigrateOpts = {
  trackerRoot: string;
  fromVersion?: TrackerVersion;
  dryRun: boolean;
};

export type MigrateResult = {
  version: TrackerVersion;
  noOp: boolean;
  logPath: string | null;
  changeCount: number;
  diffText: string;
};

export function runMigrate(opts: MigrateOpts): MigrateResult {
  const { trackerRoot, dryRun } = opts;
  const fromVersion = opts.fromVersion ?? detectVersion(trackerRoot);

  const plan = planMigration({ trackerRoot, fromVersion });
  const diffText = formatDiff({ plan, dryRun });

  if (plan.changes.length === 0) {
    return {
      version: plan.version,
      noOp: true,
      logPath: null,
      changeCount: 0,
      diffText,
    };
  }

  if (dryRun) {
    return {
      version: plan.version,
      noOp: false,
      logPath: null,
      changeCount: plan.changes.length,
      diffText,
    };
  }

  // Apply the migration — handle v1 folder creation specially
  // (need to create M1 folder before copying files)
  const v1Changes = plan.changes.filter(
    (c) => c.step === "migrateV1ToV2",
  );
  const otherChanges = plan.changes.filter(
    (c) => c.step !== "migrateV1ToV2" && c.step !== "regenerateIndex",
  );
  const indexChange = plan.changes.find((c) => c.step === "regenerateIndex");

  const timestamp = new Date().toISOString();
  const logLines: string[] = [];

  // 1. Apply v1 folder changes
  for (const change of v1Changes) {
    if (!change.destPath) continue;
    const parentDir = dirname(change.destPath);
    if (!existsSync(parentDir)) {
      mkdirSync(parentDir, { recursive: true });
    }
    atomicWriteFileSync(change.destPath, change.newContent ?? "");
    logLines.push(
      `[${timestamp}] STEP=${change.step} FILE=${change.file} ACTION=${change.action} REASON=${change.reason}`,
    );

    // For moved files, delete the source
    if (change.action === "moved") {
      const srcPath = join(trackerRoot, basename(change.destPath));
      if (existsSync(srcPath) && srcPath !== change.destPath) {
        try {
          unlinkSync(srcPath);
        } catch {
          // best effort
        }
      }
    }
  }

  // 2. Apply remaining changes (strip frontmatter, normalize dates, worklog)
  for (const change of otherChanges) {
    if (!change.destPath) continue;
    const parentDir = dirname(change.destPath);
    if (!existsSync(parentDir)) {
      mkdirSync(parentDir, { recursive: true });
    }
    atomicWriteFileSync(change.destPath, change.newContent ?? "");
    logLines.push(
      `[${timestamp}] STEP=${change.step} FILE=${change.file} ACTION=${change.action} REASON=${change.reason}`,
    );
  }

  // 3. Regenerate index
  if (indexChange) {
    try {
      const state = readTrackerState(trackerRoot);
      const indexContent = rebuildIndexDoc(state);
      const indexPath = indexChange.destPath ?? join(trackerRoot, "00-INDEX.md");
      atomicWriteFileSync(indexPath, indexContent);
      logLines.push(
        `[${timestamp}] STEP=regenerateIndex FILE=${indexChange.file} ACTION=modified REASON=regenerate 00-INDEX.md with canonical generator header`,
      );
    } catch {
      // Non-fatal — index might not be readable on partial migration
    }
  }

  // 3b. Stamp schema_version as final atomic step (idempotent).
  // If the regenerateIndex step ran, schema_version is already in the rebuilt
  // index (rebuildIndexDoc always writes CURRENT_SCHEMA_VERSION). If for any
  // reason the regenerateIndex step was skipped, do it now so the stamp is
  // guaranteed to be present.
  if (!indexChange) {
    const finalIndexPath = join(trackerRoot, "00-INDEX.md");
    if (existsSync(finalIndexPath)) {
      try {
        const state = readTrackerState(trackerRoot);
        const indexContent = rebuildIndexDoc(state);
        atomicWriteFileSync(finalIndexPath, indexContent);
        logLines.push(
          `[${timestamp}] STEP=stampSchemaVersion FILE=.tracker/00-INDEX.md ACTION=modified REASON=write schema_version: ${CURRENT_SCHEMA_VERSION} as final atomic step`,
        );
      } catch {
        // Non-fatal
      }
    }
  }

  // 4. Write migration log
  const logFileName = `.migration-${formatISOForFileName(new Date())}.log`;
  const logPath = join(trackerRoot, logFileName);
  atomicWriteFileSync(logPath, logLines.join("\n") + "\n");

  return {
    version: plan.version,
    noOp: false,
    logPath,
    changeCount: plan.changes.length,
    diffText,
  };
}
