/**
 * `worklog index` — the generated `.tracker/worklog/00-INDEX.md` (M7/03).
 *
 * A worklog directory is a pile of files an agent can only search by reading,
 * and reading them all costs more context than the work they describe. This
 * module renders one row per file — where it belongs, whether anyone is still
 * working in it, when it last moved, and a hook to recognize it by — so finding
 * the right worklog costs a single small file instead of the whole directory.
 *
 * Same contract as the main index: the CLI is the sole author, the file carries
 * a do-not-edit header, and the output is a pure function of the directory's
 * *contents* — running it twice writes identical bytes, and so does running it
 * in a fresh clone. Nothing here reads a file's mtime: this index is committed,
 * and git does not preserve mtimes, so an mtime-derived date would churn the
 * file on every clone.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { atomicWriteFileSync } from "./atomic.ts";
import { scanWorklogDir, type WorklogFileScan, worklogThreadActivity } from "./worklog.ts";

/** Basename of the generated index inside `.tracker/worklog/`. */
export const WORKLOG_INDEX_FILE = "00-INDEX.md";

const GENERATED_HEADER =
  "<!-- Generated by tracker CLI. Do not edit; run `tracker worklog index`. -->";

/** The hook is a recognition cue, not a summary — longer ones get cut. */
const HOOK_MAX_CHARS = 60;

/** A worklog file named after a milestone: `M7-worklog-dreaming.md` → `M7`. */
const MILESTONE_RE = /^(M\d+)-/i;

const STATE_LEGEND = `## State Legend

- \`active\` — at least one open thread; someone may still be working here
- \`closed\` — every thread closed (an empty file reads as \`closed\` too)
- \`legacy\` — pre-CLI freeform prose with no threads at all
- \`distilled\` — replaced by an anchor stub; the original is under \`archive/worklog-raw/\``;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type WorklogIndexState = "active" | "closed" | "legacy" | "distilled";

export type WorklogIndexRow = {
  /** Basename inside `.tracker/worklog/`. */
  file: string;
  /** Milestone code from the filename (`M7`), or null for cross-cutting files. */
  milestone: string | null;
  state: WorklogIndexState;
  openThreads: number;
  totalThreads: number;
  /**
   * `YYYY-MM-DD` derived from file content, or null when the content carries no
   * date at all (pre-CLI prose) — never from the filesystem. Renders as `—`.
   */
  lastActivity: string | null;
  /**
   * First entry's opening line, else the first thread's label, else the file's
   * H1, truncated. `—` when the file offers none of them.
   */
  hook: string;
};

export type WorklogIndexResult = {
  /** Absolute path written. */
  path: string;
  rows: WorklogIndexRow[];
};

// ---------------------------------------------------------------------------
// Rows
// ---------------------------------------------------------------------------

/**
 * One row per worklog file, in display order. Generated `00-` files are already
 * filtered out by {@link scanWorklogDir}, so the index never lists itself.
 */
export function collectWorklogIndexRows(trackerRoot: string): WorklogIndexRow[] {
  return scanWorklogDir(trackerRoot).map(buildRow).sort(compareRows);
}

function buildRow(scan: WorklogFileScan): WorklogIndexRow {
  const threads = scan.doc.threads;
  const openThreads = threads.filter((t) => !t.closedAt).length;
  const activity = deriveLastActivity(scan);

  return {
    file: scan.file,
    milestone: MILESTONE_RE.exec(scan.file)?.[1]?.toUpperCase() ?? null,
    state: deriveState(scan, openThreads),
    openThreads,
    totalThreads: threads.length,
    lastActivity: activity === null ? null : activity.slice(0, 10),
    hook: deriveHook(scan),
  };
}

/**
 * `active` wins outright — an open thread is the one signal a reader must not
 * miss, and it is the only state that implies someone may still be writing
 * here. `distilled` then beats `legacy` (spec 02): a stub is thread-less prose
 * by construction and would otherwise be mistaken for pre-CLI leftovers. A file
 * whose threads are all closed, a mixed file with folded legacy headings, and
 * an empty file all read as `closed`; `legacy` is reserved for files with no
 * threads at all, which is exactly what the spec-01 flag marks.
 */
function deriveState(scan: WorklogFileScan, openThreads: number): WorklogIndexState {
  if (openThreads > 0) return "active";
  if (scan.state === "distilled") return "distilled";
  if (scan.doc.threads.length === 0 && scan.legacy) return "legacy";
  return "closed";
}

/**
 * The newest date the file's own bytes can prove, so a fresh clone regenerates
 * the same index the repo already has committed.
 *
 * Threads date themselves. A distilled stub has no threads but does carry a
 * provenance stamp, and the moment it was distilled is the last thing that
 * genuinely happened to it. Pre-CLI prose proves nothing, so it stays dateless
 * rather than borrowing an mtime that git will not carry across a clone —
 * {@link compareRows} sorts those rows to the tail by filename.
 */
function deriveLastActivity(scan: WorklogFileScan): string | null {
  return worklogThreadActivity(scan.doc) ?? scan.stamp?.distilledAt ?? null;
}

/**
 * Something a reader can recognize the file by.
 *
 * The first entry's text comes first because it is the one line a human wrote
 * about the work: `worklog open <slug> --message "<task>"` stores the slug as
 * the thread label and the message as entry one, so a label-first hook restates
 * the filename in the Hook column and the row says nothing the File column did
 * not. Label is the fallback for a thread opened without a message, and the H1
 * for thread-less files.
 */
function deriveHook(scan: WorklogFileScan): string {
  const firstThread = scan.doc.threads[0];

  const entryText = firstThread?.entries.find((e) => (e.text ?? "").trim() !== "")?.text ?? "";
  const firstLine = entryText.split("\n").find((l) => l.trim() !== "")?.trim() ?? "";
  if (firstLine !== "") return truncateHook(firstLine);

  const label = firstThread?.label?.trim() ?? "";
  if (label !== "") return truncateHook(label);

  for (const line of scan.doc.preamble) {
    const heading = /^#\s+(.+)$/.exec(line.trim());
    if (heading) {
      const text = (heading[1] ?? "").trim();
      if (text !== "") return truncateHook(text);
    }
  }

  return "—";
}

/**
 * Flatten to one line, cut to {@link HOOK_MAX_CHARS}, then escape table pipes.
 * Escaping last keeps the visible length honest — a `\|` is one character to
 * the reader.
 */
function truncateHook(text: string): string {
  const flat = text.replace(/\s+/g, " ").trim();
  const cut =
    flat.length <= HOOK_MAX_CHARS
      ? flat
      : `${flat.slice(0, HOOK_MAX_CHARS - 1).trimEnd()}…`;
  return cut.replace(/\|/g, "\\|");
}

/**
 * Active files first, then newest activity first. Dateless rows (pre-CLI prose)
 * sort as the empty string, which puts them last as a block. Filename breaks
 * every tie — including the all-dateless tie — so the ordering is total and the
 * rendered file is byte-stable across runs and across clones.
 */
function compareRows(a: WorklogIndexRow, b: WorklogIndexRow): number {
  const aActive = a.state === "active" ? 0 : 1;
  const bActive = b.state === "active" ? 0 : 1;
  if (aActive !== bActive) return aActive - bActive;

  const aDate = a.lastActivity ?? "";
  const bDate = b.lastActivity ?? "";
  if (aDate > bDate) return -1;
  if (aDate < bDate) return 1;

  if (a.file < b.file) return -1;
  if (a.file > b.file) return 1;
  return 0;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/**
 * Render the index document. Pure — no clock, no filesystem — so the same rows
 * always produce the same bytes.
 */
export function renderWorklogIndexDoc(rows: WorklogIndexRow[]): string {
  const lines: string[] = [];

  lines.push(GENERATED_HEADER);
  lines.push("");
  lines.push("---");
  lines.push("type: worklog-index");
  lines.push("version: 1");
  lines.push("---");
  lines.push("");
  lines.push("# Worklog Index");
  lines.push("");
  lines.push(
    "One row per file in `.tracker/worklog/`. Find the worklog you need here, then open only that file.",
  );
  lines.push("");

  if (rows.length === 0) {
    lines.push("_No worklogs yet_");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("| File | Milestone | State | Open/Total | Last activity | Hook |");
  lines.push("|------|-----------|-------|------------|---------------|------|");

  for (const row of rows) {
    lines.push(
      `| [${row.file}](${row.file}) | ${row.milestone ?? "—"} | ${row.state} | ` +
        `${row.openThreads}/${row.totalThreads} | ${row.lastActivity ?? "—"} | ${row.hook} |`,
    );
  }

  lines.push("");
  lines.push(STATE_LEGEND);
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

/**
 * Regenerate `.tracker/worklog/00-INDEX.md`. Returns null — not an error — when
 * there is no worklog directory: projects that never opened a thread have
 * nothing to index, and `tracker index --rebuild` must not fail for them.
 */
export function rebuildWorklogIndex(trackerRoot: string): WorklogIndexResult | null {
  const worklogDir = join(trackerRoot, "worklog");
  if (!existsSync(worklogDir)) {
    return null;
  }

  const rows = collectWorklogIndexRows(trackerRoot);
  const path = join(worklogDir, WORKLOG_INDEX_FILE);
  const content = renderWorklogIndexDoc(rows);

  // Skip the write when nothing changed: the index rides every `index --rebuild`,
  // and rewriting an identical file only churns mtimes that other tooling reads.
  if (!existsSync(path) || readFileSync(path, "utf-8") !== content) {
    atomicWriteFileSync(path, content);
  }

  return { path, rows };
}
