/**
 * Shared fixtures and helpers for schema versioning tests.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { initTracker, addMilestone } from "../../lib/tracker-writer.ts";
import { parseFrontmatter } from "../../lib/markdown/frontmatter.ts";

export const MIGRATIONS_FIXTURES_DIR = join(
  import.meta.dirname ?? new URL(".", import.meta.url).pathname,
  "../fixtures/migrations",
);

/** Build a valid spec content string */
export function makeValidSpec(): string {
  return `---
updated: 2026-01-01
agent: test
depends_on: []
---

# Valid Spec

## Verification Checklist

### Implementation

- [ ] First task
`;
}

/** Build a spec with a dangling depends_on (creates a doctor finding) */
export function makeDanglingSpec(): string {
  return `---
updated: 2026-01-01
agent: test
depends_on:
  - .tracker/M99-nonexistent/99-ghost.md
---

# Dangling Spec

## Verification Checklist

### Implementation

- [ ] A task
`;
}

/** Build an 00-INDEX.md without schema_version (has generated comment header) */
export function makeUnstampedIndex(): string {
  return `<!-- Generated by tracker CLI. Do not edit; run \`tracker index --rebuild\`. -->

---
name: Test Tracker
type: main-index
version: 2
---

# Test — Tracker

## Progress Dashboard

| Milestone | Name | Progress | Verified | Status |
|-----------|------|----------|----------|--------|
| M1 | Test Milestone | ░░░░░░░░░░ 0% | 0/1 | Not Started |

## Current Focus

### M1 — Test Milestone

| Spec | Verified | Status |
|------|----------|--------|
| 01-valid.md | 0/1 | Not Started |

### Next Action
**Spec:** \`01-valid.md\` — Valid Spec
**Task:** First task
**Status:** Pending

## Blockers

None

---

## Status Legend

- \`[x]\` — Verified (implementation complete, tests pass)
- \`[ ]\` — Pending (not started)
- \`[~]\` — In Progress (actively being worked on)
- \`[!]\` — Blocked (has dependency, can't proceed)
- \`[-]\` — Skipped (intentionally not implementing)

## Archived Milestones

_None yet_
`;
}

/**
 * Build an index with a specific schema_version in the frontmatter.
 * Frontmatter starts at line 1 so gray-matter can parse it directly.
 * Used for tests that need to inject a specific version number.
 */
export function makeIndexWithVersion(version: number): string {
  return `---
name: Test Tracker
schema_version: ${version}
type: main-index
version: 2
---

<!-- Generated by tracker CLI. Do not edit; run \`tracker index --rebuild\`. -->

# Test — Tracker

## Progress Dashboard

| Milestone | Name | Progress | Verified | Status |
|-----------|------|----------|----------|--------|
| M1 | Test Milestone | ░░░░░░░░░░ 0% | 0/1 | Not Started |

## Blockers

None
`;
}

/** Read schema_version from the 00-INDEX.md frontmatter */
export function readIndexSchemaVersion(trackerRoot: string): number | null {
  const indexPath = join(trackerRoot, "00-INDEX.md");
  const raw = readFileSync(indexPath, "utf-8");
  // Strip leading HTML comment (generated header) so gray-matter can find frontmatter
  const stripped = raw.replace(/^<!--[\s\S]*?-->\s*/m, "");
  const { data } = parseFrontmatter(stripped);
  const v = data["schema_version"];
  return typeof v === "number" ? v : null;
}

/**
 * Set up a clean tracker with one milestone and one valid spec.
 * The fresh tracker already has schema_version: 2 from rebuildIndexDoc.
 */
export function setupCleanTracker(tmpDir: string): string {
  initTracker({ projectRoot: tmpDir });
  const trackerRoot = join(tmpDir, ".tracker");
  addMilestone({
    trackerRoot,
    name: "Test Milestone",
    slug: "test-milestone",
    owner: "dev@example.com",
  });
  const milestonePath = join(trackerRoot, "M1-test-milestone");
  writeFileSync(join(milestonePath, "01-valid.md"), makeValidSpec(), "utf-8");
  return trackerRoot;
}
