/**
 * Tests for `tracker index --rebuild`.
 *
 * pnpm vitest run index-rebuild
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initTracker, addMilestone, addSpec, rebuildIndex } from "../lib/tracker-writer.ts";

const SAMPLE_SPEC = `---
status: Not Started
updated: 2026-01-01
agent: test
---

# My Spec

## Verification Checklist

- [ ] Task one
- [ ] Task two
`;

describe("index-rebuild", () => {
  let tmpDir: string;
  let trackerRoot: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tracker-index-rebuild-test-"));
    initTracker({ projectRoot: tmpDir });
    trackerRoot = join(tmpDir, ".tracker");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("generates 00-INDEX.md with do-not-edit header", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("Generated by tracker CLI");
    expect(content).toContain("tracker index --rebuild");
  });

  it("contains Progress Dashboard table", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("Progress Dashboard");
  });

  it("includes milestone entries in dashboard", () => {
    addMilestone({
      trackerRoot,
      name: "My Milestone",
      slug: "my-milestone",
      owner: "dev@example.com",
    });
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("My Milestone");
  });

  it("includes spec entries in Current Focus section", () => {
    addMilestone({
      trackerRoot,
      name: "My Milestone",
      slug: "my-milestone",
      owner: "dev@example.com",
    });
    // Write a spec manually
    const specPath = join(trackerRoot, "M1-my-milestone", "01-my-spec.md");
    writeFileSync(specPath, SAMPLE_SPEC, "utf-8");

    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("01-my-spec.md");
  });

  it("is idempotent: rebuilding twice produces identical output", () => {
    addMilestone({
      trackerRoot,
      name: "My Milestone",
      slug: "my-milestone",
      owner: "dev@example.com",
    });
    const specPath = join(trackerRoot, "M1-my-milestone", "01-my-spec.md");
    writeFileSync(specPath, SAMPLE_SPEC, "utf-8");

    rebuildIndex(trackerRoot);
    const first = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");

    rebuildIndex(trackerRoot);
    const second = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");

    expect(first).toBe(second);
  });

  it("contains Status Legend", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("Status Legend");
  });

  it("contains Archived Milestones section", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("Archived Milestones");
  });

  it("renders _None yet_ when no archive directory exists", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("_None yet_");
  });

  it("renders archived milestones scanned from .tracker/archive/", () => {
    const archiveDir = join(trackerRoot, "archive");
    mkdirSync(archiveDir);
    writeFileSync(
      join(archiveDir, "M5-old-work.md"),
      `---
name: Old Work
slug: M5-old-work
archived: 2026-06-01
completed: 2026-05-30
---

# Old Work — Archive

Summary.
`,
      "utf-8",
    );

    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).not.toContain("_None yet_");
    expect(content).toContain("- [Old Work](archive/M5-old-work.md) — archived 2026-06-01");
  });

  it("falls back to heading and filename when archive frontmatter is sparse", () => {
    const archiveDir = join(trackerRoot, "archive");
    mkdirSync(archiveDir);
    writeFileSync(
      join(archiveDir, "M3-bare.md"),
      `# Bare Milestone — Archive

No frontmatter at all.
`,
      "utf-8",
    );

    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("- [Bare Milestone — Archive](archive/M3-bare.md)");
  });

  it("archived section survives repeated rebuilds (issue #5 repro)", () => {
    const archiveDir = join(trackerRoot, "archive");
    mkdirSync(archiveDir);
    writeFileSync(
      join(archiveDir, "M1-done.md"),
      `---
name: Done Milestone
archived: 2026-06-02
---

# Done Milestone
`,
      "utf-8",
    );

    rebuildIndex(trackerRoot);
    const first = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    rebuildIndex(trackerRoot);
    const second = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");

    expect(first).toContain("Done Milestone");
    expect(second).toBe(first);
  });

  it("contains Blockers section", () => {
    rebuildIndex(trackerRoot);
    const content = readFileSync(join(trackerRoot, "00-INDEX.md"), "utf-8");
    expect(content).toContain("Blockers");
  });
});
