/**
 * `tracker index --rebuild` also rebuilds the worklog index (M7/03).
 *
 * The worklog index is only useful if it stays current, and the thing that
 * already runs at every checkpoint — update-index, wrap-up — is `index
 * --rebuild`. So it piggybacks there. The two facts worth pinning: it actually
 * happens, and a project without a worklog directory is not an error.
 *
 * pnpm vitest run worklog-index-rebuild
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { initTracker } from "../lib/tracker-writer.ts";
import { WORKLOG_INDEX_FILE } from "../lib/worklog-index.ts";

const THREAD = [
  "# Worklog — M9 auth",
  "",
  "## 01ABCDEFGHJKMNPQRST1-auth — rotate the signing keys",
  "<!-- opened: 2026-03-10T09:00:00.000Z -->",
  "",
].join("\n");

describe("index --rebuild rebuilds the worklog index", () => {
  let tmpDir: string;
  let trackerRoot: string;
  let worklogDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tracker-worklog-index-rebuild-"));
    initTracker({ projectRoot: tmpDir });
    trackerRoot = join(tmpDir, ".tracker");
    worklogDir = join(trackerRoot, "worklog");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function runTracker(args: string[]): { stdout: string; stderr: string; exitCode: number } {
    const result = spawnSync(
      "node",
      [
        "--experimental-strip-types",
        "--no-warnings",
        join(process.cwd(), "bin/tracker.mts"),
        ...args,
      ],
      { encoding: "utf-8", cwd: tmpDir, timeout: 30_000 },
    );
    return {
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
      exitCode: result.status ?? -1,
    };
  }

  const indexPath = (): string => join(worklogDir, WORKLOG_INDEX_FILE);

  it("writes worklog/00-INDEX.md alongside the main index", () => {
    mkdirSync(worklogDir, { recursive: true });
    writeFileSync(join(worklogDir, "M9-auth.md"), THREAD, "utf-8");

    const { stdout, exitCode } = runTracker(["index", "--rebuild"]);
    expect(exitCode).toBe(0);
    expect(stdout).toContain(join(trackerRoot, "00-INDEX.md"));
    expect(stdout).toContain(indexPath());
    expect(stdout).toContain("(1 worklog file(s))");

    const content = readFileSync(indexPath(), "utf-8");
    expect(content.split("\n")[0]).toBe(
      "<!-- Generated by darius. Do not edit; run `darius worklog index`. -->",
    );
    expect(content).toContain("[M9-auth.md](M9-auth.md)");
  });

  it("picks up a worklog file added after the previous rebuild", () => {
    mkdirSync(worklogDir, { recursive: true });
    writeFileSync(join(worklogDir, "M9-auth.md"), THREAD, "utf-8");
    expect(runTracker(["index", "--rebuild"]).exitCode).toBe(0);

    writeFileSync(
      join(worklogDir, "M8-storage.md"),
      [
        "## 01ABCDEFGHJKMNPQRST2-alpha — alpha",
        "<!-- opened: 2026-02-01T09:00:00.000Z -->",
        "<!-- closed: 2026-02-02T09:00:00.000Z status: done -->",
        "",
      ].join("\n"),
      "utf-8",
    );

    expect(runTracker(["index", "--rebuild"]).exitCode).toBe(0);
    const content = readFileSync(indexPath(), "utf-8");
    expect(content).toContain("[M8-storage.md](M8-storage.md)");
    expect(content).toContain("[M9-auth.md](M9-auth.md)");
  });

  it("is a silent no-op when the project has no worklog directory", () => {
    expect(existsSync(worklogDir)).toBe(false);

    const { stdout, stderr, exitCode } = runTracker(["index", "--rebuild"]);
    expect(exitCode).toBe(0);
    expect(stderr).toBe("");
    expect(stdout).toContain("darius index: rebuilt");
    expect(stdout).not.toContain("worklog file(s)");
    expect(existsSync(worklogDir)).toBe(false);
  });

  it("running --rebuild twice leaves the worklog index byte-identical", () => {
    mkdirSync(worklogDir, { recursive: true });
    writeFileSync(join(worklogDir, "M9-auth.md"), THREAD, "utf-8");

    expect(runTracker(["index", "--rebuild"]).exitCode).toBe(0);
    const first = readFileSync(indexPath(), "utf-8");
    expect(runTracker(["index", "--rebuild"]).exitCode).toBe(0);
    expect(readFileSync(indexPath(), "utf-8")).toBe(first);
  });
});
