/**
 * IndexDoc generator-input types — no external dependencies.
 *
 * IMPORTANT: This is a generator-only module. It describes the INPUT that the
 * `darius index --rebuild` command accepts to generate a 00-INDEX.md file.
 *
 * There is NO parseIndex() or parseIndexDoc() function here — index files are
 * generated, not parsed back. Every generated file carries the header:
 *
 *   <!-- Generated by darius. Do not edit; run `darius index --rebuild`. -->
 *
 * If you find yourself wanting to parse an index file, you're looking for
 * the Milestone schema instead.
 */

import { CURRENT_SCHEMA_VERSION } from "../version.ts";
import { TrackerValidationError } from "../markdown/errors.ts";

// ---------------------------------------------------------------------------
// Spec entry (one row in the specs table)
// ---------------------------------------------------------------------------

export type SpecStatus = "Not Started" | "In Progress" | "Complete" | "Blocked";

export interface IndexSpecEntry {
  /** Relative path to the spec file from the milestone directory */
  path: string;
  /** Spec title (first H1 heading) */
  title: string;
  /** Derived status */
  status: SpecStatus;
  /** Number of verified checklist items */
  verified: number;
  /** Total number of checklist items */
  total: number;
}

// ---------------------------------------------------------------------------
// IndexDocGeneratorInput
// ---------------------------------------------------------------------------

export interface IndexDocGeneratorInput {
  /** Milestone slug, e.g. "M2-tracker-cli-refactor" */
  milestoneSlug: string;
  /** Milestone name / title */
  milestoneName: string;
  /** ISO date when the index was generated */
  generatedAt: string;
  /** Ordered list of spec entries */
  specs: IndexSpecEntry[];
  /** Optional lessons section content (markdown) */
  lessons?: string;
  /** On-disk schema version stamp — always written by the generator */
  schema_version: number;
}

// ---------------------------------------------------------------------------
// Validators
// ---------------------------------------------------------------------------

const VALID_SPEC_STATUSES: SpecStatus[] = [
  "Not Started",
  "In Progress",
  "Complete",
  "Blocked",
];

function validateIndexSpecEntry(
  raw: unknown,
  path: string,
  sourcePath?: string,
): IndexSpecEntry {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new TrackerValidationError({
      path,
      expected: "object",
      actual: Array.isArray(raw) ? "array" : typeof raw,
      sourcePath,
    });
  }
  const d = raw as Record<string, unknown>;

  if (typeof d["path"] !== "string") {
    throw new TrackerValidationError({ path: `${path}.path`, expected: "string", actual: typeof d["path"], sourcePath });
  }
  if (typeof d["title"] !== "string") {
    throw new TrackerValidationError({ path: `${path}.title`, expected: "string", actual: typeof d["title"], sourcePath });
  }
  if (typeof d["status"] !== "string" || !(VALID_SPEC_STATUSES as string[]).includes(d["status"])) {
    throw new TrackerValidationError({
      path: `${path}.status`,
      expected: VALID_SPEC_STATUSES.join(" | "),
      actual: typeof d["status"] === "string" ? d["status"] : typeof d["status"],
      sourcePath,
    });
  }
  if (typeof d["verified"] !== "number" || !Number.isInteger(d["verified"]) || d["verified"] < 0) {
    throw new TrackerValidationError({ path: `${path}.verified`, expected: "non-negative integer", actual: typeof d["verified"], sourcePath });
  }
  if (typeof d["total"] !== "number" || !Number.isInteger(d["total"]) || d["total"] < 0) {
    throw new TrackerValidationError({ path: `${path}.total`, expected: "non-negative integer", actual: typeof d["total"], sourcePath });
  }

  return {
    path: d["path"],
    title: d["title"],
    status: d["status"] as SpecStatus,
    verified: d["verified"],
    total: d["total"],
  };
}

function validateIndexDocGeneratorInput(
  raw: unknown,
  sourcePath?: string,
): IndexDocGeneratorInput {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new TrackerValidationError({
      path: "(root)",
      expected: "object",
      actual: Array.isArray(raw) ? "array" : typeof raw,
      sourcePath,
    });
  }
  const d = raw as Record<string, unknown>;

  if (typeof d["milestoneSlug"] !== "string") {
    throw new TrackerValidationError({ path: "milestoneSlug", expected: "string", actual: typeof d["milestoneSlug"], sourcePath });
  }
  if (typeof d["milestoneName"] !== "string") {
    throw new TrackerValidationError({ path: "milestoneName", expected: "string", actual: typeof d["milestoneName"], sourcePath });
  }
  if (typeof d["generatedAt"] !== "string") {
    throw new TrackerValidationError({ path: "generatedAt", expected: "string", actual: typeof d["generatedAt"], sourcePath });
  }
  if (!Array.isArray(d["specs"])) {
    throw new TrackerValidationError({ path: "specs", expected: "array", actual: typeof d["specs"], sourcePath });
  }
  if (typeof d["schema_version"] !== "number" || !Number.isInteger(d["schema_version"]) || d["schema_version"] < 1) {
    throw new TrackerValidationError({ path: "schema_version", expected: "positive integer", actual: typeof d["schema_version"], sourcePath });
  }

  const specs = d["specs"].map((spec, i) =>
    validateIndexSpecEntry(spec, `specs[${i}]`, sourcePath),
  );

  return {
    milestoneSlug: d["milestoneSlug"],
    milestoneName: d["milestoneName"],
    generatedAt: d["generatedAt"],
    specs,
    lessons: typeof d["lessons"] === "string" ? d["lessons"] : undefined,
    schema_version: d["schema_version"],
  };
}

// ---------------------------------------------------------------------------
// Schema-compatible API shims
// ---------------------------------------------------------------------------

export const IndexDocGeneratorInputSchema = {
  safeParse(
    data: unknown,
  ): { success: true; data: IndexDocGeneratorInput } | { success: false; error: { message: string } } {
    try {
      return { success: true, data: validateIndexDocGeneratorInput(data) };
    } catch (err) {
      return { success: false, error: { message: err instanceof Error ? err.message : String(err) } };
    }
  },

  parse(data: unknown): IndexDocGeneratorInput {
    return validateIndexDocGeneratorInput(data);
  },
};

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generate the content of a 00-INDEX.md file from the given input.
 *
 * The output always starts with the "do not edit" comment so tooling can
 * detect generated files.
 */
export function generateIndexDoc(input: IndexDocGeneratorInput): string {
  const validated = validateIndexDocGeneratorInput(input);

  const rows = validated.specs
    .map((s) => {
      const progress =
        s.total > 0 ? `${s.verified}/${s.total}` : "—";
      return `| [${s.title}](${s.path}) | ${s.status} | ${progress} |`;
    })
    .join("\n");

  const lessonsSection =
    validated.lessons
      ? `\n\n## Lessons\n\n${validated.lessons}`
      : "\n\n## Lessons\n\n<!-- populated by /tracker:enrich when the milestone completes -->";

  return [
    `<!-- Generated by darius. Do not edit; run \`darius index --rebuild\`. -->`,
    "",
    `---`,
    `name: ${validated.milestoneName}`,
    `schema_version: ${CURRENT_SCHEMA_VERSION}`,
    `slug: ${validated.milestoneSlug}`,
    `generated: ${validated.generatedAt}`,
    `---`,
    "",
    `# ${validated.milestoneName}`,
    "",
    "## Specs",
    "",
    "| Spec | Status | Progress |",
    "| ---- | ------ | -------- |",
    rows,
    lessonsSection,
    "",
  ].join("\n");
}
